#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias zshconfig="$EDITOR ~/.zshrc"
alias v2ray="~/dev/v2ray-macos/v2ray -config ~/dev/v2ray-macos/config.json &"
alias kv2="pkill -9 v2ray"
#alias ssh="TERM=xterm-256color ssh"

export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
